### ISSUE TITLE
Can no longer build logspout-kinesis due to AWS library change

### ISSUE THREAD

**Issue by crohr** [remind101/logspout-kinesis#22]
When I run `docker build`, I now get:

```
# github.com/remind101/logspout-kinesis
../../remind101/logspout-kinesis/stream.go:39: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to kinesis.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
```

It looks like AWS broke backwards compatibility in its recent release. This [comment](https://github.com/mitchellh/packer/issues/2890#issuecomment-152615106) sheds more light on the issue.

**Comment by benguillet** [comment]
@crohr Should be fixed by #23. Thanks for reporting!
